// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMpFukE8R7KBU8xvsTN5Alb-Hqrr3mhY',
    appId: '1:241347517776:web:f964ca509f9cd57773e055',
    messagingSenderId: '241347517776',
    projectId: 'gym-genius-f35e2',
    authDomain: 'gym-genius-f35e2.firebaseapp.com',
    storageBucket: 'gym-genius-f35e2.firebasestorage.app',
    measurementId: 'G-ZT50NXCVG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGkd4GWx0MIIj7DMt3xSCaiXM8BmBPJrQ',
    appId: '1:241347517776:android:4e855e0d8b75c8e973e055',
    messagingSenderId: '241347517776',
    projectId: 'gym-genius-f35e2',
    storageBucket: 'gym-genius-f35e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUF7n7JTqOsMOncDs7OTLqhiOw0MHXYN0',
    appId: '1:241347517776:ios:5bee41512abc82fe73e055',
    messagingSenderId: '241347517776',
    projectId: 'gym-genius-f35e2',
    storageBucket: 'gym-genius-f35e2.firebasestorage.app',
    iosBundleId: 'com.example.gymGenius',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUF7n7JTqOsMOncDs7OTLqhiOw0MHXYN0',
    appId: '1:241347517776:ios:5bee41512abc82fe73e055',
    messagingSenderId: '241347517776',
    projectId: 'gym-genius-f35e2',
    storageBucket: 'gym-genius-f35e2.firebasestorage.app',
    iosBundleId: 'com.example.gymGenius',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdMpFukE8R7KBU8xvsTN5Alb-Hqrr3mhY',
    appId: '1:241347517776:web:20272f55a4cd591473e055',
    messagingSenderId: '241347517776',
    projectId: 'gym-genius-f35e2',
    authDomain: 'gym-genius-f35e2.firebaseapp.com',
    storageBucket: 'gym-genius-f35e2.firebasestorage.app',
    measurementId: 'G-C2X6LMBGN8',
  );
}
